version: '2'
services:
    web:
        image: loweb/web
        container_name: loweb
        environment:
            APP_ENV: local-docker
        build: ./web
        ports:
            - '81:80'
        volumes:
            - ../:/work/
        depends_on:
            - mysql
    mysql:
        image: loweb/mysql
        build: ./db
        container_name: loweb-database
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        volumes:
            - ./db/sqldumps/:/sqldumps/
